name: WormholeXTreme
main: de.luricos.bukkit.WormholeXTreme.Wormhole.bukkit.WormholeXTreme
version: 2.0
authors: [lycano]
softdepend: [PermissionsEx]
description: >
             Wormhole X-Treme! Wormholes as travel portals. Splash Effect, IDC,
             Iris, configurable Wormhole materials, and much much more.
             
commands:
   wormhole:
     description: Wormhole administration and configuration commands.
     aliases: [wxt]
     usage: |
            /<command> - display help
            /<command> gate info [GateName] - Print gate info for selected Wormhole
            /<command> gate create <GateName> - Creates a gate with the given name